name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/igorrebeche/index.json
        include-prerelease: true
    # Authenticates packages to push to GPR
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build
    - name: Create the package
      run: dotnet pack --configuration Release events
    - name: Publish the package to GPR
      run: dotnet nuget push market-price-binance-collector-service/bin/Release/*.nupkg
